# Housing Price Classification

Goal: predict whether a house is classified as expensive using housing features.

Target variable: Expensive

Problem type: binary classification

Final output: predictions for the competition test set

## train/test split, imputing missing values and preprocessing pipeline ##

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.compose import make_column_transformer
from sklearn import set_config
set_config(transform_output='pandas')

data = pd.read_csv("data/housing_iteration_5_classification.csv")

In [130]:
data.columns

Index(['LotArea', 'LotFrontage', 'TotalBsmtSF', 'BedroomAbvGr', 'Fireplaces',
       'PoolArea', 'GarageCars', 'WoodDeckSF', 'ScreenPorch', 'Expensive',
       'MSZoning', 'Condition1', 'Heating', 'Street', 'CentralAir',
       'Foundation', 'ExterQual', 'ExterCond', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'KitchenQual', 'FireplaceQu',
       'MSSubClass', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', '1stFlrSF',
       '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath',
       'FullBath', 'HalfBath', 'KitchenAbvGr', 'TotRmsAbvGrd', 'GarageYrBlt',
       'GarageArea', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'MiscVal',
       'MoSold', 'YrSold', 'Id', 'Alley', 'LotShape', 'LandContour',
       'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'BsmtFinType2', 'HeatingQC', 'Electrical',
       'Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond',
       'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType',
       'SaleCondition'],
      dtype='str')

In [131]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   LotArea        1460 non-null   int64
 1   LotFrontage    1201 non-null   float64
 2   TotalBsmtSF    1460 non-null   int64
 3   BedroomAbvGr   1460 non-null   int64
 4   Fireplaces     1460 non-null   int64
 5   PoolArea       1460 non-null   int64
 6   GarageCars     1460 non-null   int64
 7   WoodDeckSF     1460 non-null   int64
 8   ScreenPorch    1460 non-null   int64
 9   Expensive      1460 non-null   int64
 10  MSZoning       1460 non-null   str
 11  Condition1     1460 non-null   str
 12  Heating        1460 non-null   str
 13  Street         1460 non-null   str
 14  CentralAir     1460 non-null   str
 15  Foundation     1460 non-null   str
 16  ExterQual      1460 non-null   str
 17  ExterCond      1460 non-null   str
 18  BsmtQual       1423 non-null   str
 19  BsmtCond       1423 non-null   str
 20  BsmtExposure   1422 non-null   str
 21  BsmtFinType1   1423 non-null   str
 22  KitchenQual    1460 non-null   str
 23  FireplaceQu    770 non-null    str
 24  MSSubClass     1460 non-null   int64
 25  OverallQual    1460 non-null   int64
 26  OverallCond    1460 non-null   int64
 27  YearBuilt      1460 non-null   int64
 28  YearRemodAdd   1460 non-null   int64
 29  MasVnrArea     1452 non-null   float64
 30  BsmtFinSF1     1460 non-null   int64
 31  BsmtFinSF2     1460 non-null   int64
 32  BsmtUnfSF      1460 non-null   int64
 33  1stFlrSF       1460 non-null   int64
 34  2ndFlrSF       1460 non-null   int64
 35  LowQualFinSF   1460 non-null   int64
 36  GrLivArea      1460 non-null   int64
 37  BsmtFullBath   1460 non-null   int64
 38  BsmtHalfBath   1460 non-null   int64
 39  FullBath       1460 non-null   int64
 40  HalfBath       1460 non-null   int64
 41  KitchenAbvGr   1460 non-null   int64
 42  TotRmsAbvGrd   1460 non-null   int64
 43  GarageYrBlt    1379 non-null   float64
 44  GarageArea     1460 non-null   int64
 45  OpenPorchSF    1460 non-null   int64
 46  EnclosedPorch  1460 non-null   int64
 47  3SsnPorch      1460 non-null   int64
 48  MiscVal        1460 non-null   int64
 49  MoSold         1460 non-null   int64
 50  YrSold         1460 non-null   int64
 51  Id             1460 non-null   int64
 52  Alley          91 non-null     str
 53  LotShape       1460 non-null   str
 54  LandContour    1460 non-null   str
 55  Utilities      1460 non-null   str
 56  LotConfig      1460 non-null   str
 57  LandSlope      1460 non-null   str
 58  Neighborhood   1460 non-null   str
 59  Condition2     1460 non-null   str
 60  BldgType       1460 non-null   str
 61  HouseStyle     1460 non-null   str
 62  RoofStyle      1460 non-null   str
 63  RoofMatl       1460 non-null   str
 64  Exterior1st    1460 non-null   str
 65  Exterior2nd    1460 non-null   str
 66  MasVnrType     588 non-null    str
 67  BsmtFinType2   1422 non-null   str
 68  HeatingQC      1460 non-null   str
 69  Electrical     1459 non-null   str
 70  Functional     1460 non-null   str
 71  GarageType     1379 non-null   str
 72  GarageFinish   1379 non-null   str
 73  GarageQual     1379 non-null   str
 74  GarageCond     1379 non-null   str
 75  PavedDrive     1460 non-null   str
 76  PoolQC         7 non-null      str
 77  Fence          281 non-null    str
 78  MiscFeature    54 non-null     str
 79  SaleType       1460 non-null   str
 80  SaleCondition  1460 non-null   str
dtypes: float64(3), int64(35), str(43)
memory usage: 924.0 KB

In [ ]:
# Drop columns that are not useful for prediction

data.drop(columns=["Alley", "PoolQC", "MiscFeature", "Id"], inplace=True)

# Dropped Id because it is only an identifier.
# Dropped Alley, PoolQC, and MiscFeature because they contain many missing values.

In [133]:
# Separate the target variable from the features

X = data.copy()
y = X.pop("Expensive")


# Train-Test Split

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=42)

In [134]:
# Preprocessing Pipelines

# Identify numerical and categorical features
num_features = X.select_dtypes(include="number").columns
cat_features = X.select_dtypes(exclude="number").columns

# Numerical pipeline: Impute missing values using the mean.
num_pipe = make_pipeline(SimpleImputer(strategy="mean"))

# Categorical preprocessing:
# - Impute missing categorical values with a constant 'N_A'
cat_imputer = SimpleImputer(strategy="constant", fill_value="N_A")

In [135]:
# For ordinal encoding, specify the feature and its explicit order.
ordinal_features = ["Utilities", "ExterQual", "ExterCond", "BsmtQual", "BsmtCond", "BsmtFinType1", "BsmtFinType2", "HeatingQC", "KitchenQual", "FireplaceQu", "GarageQual", "GarageCond", "Fence", "BsmtExposure", "GarageFinish", "PavedDrive", "LotShape", "LandSlope", "Functional"]
utilities_categories = ["N_A", "ELO", "NoSeWa", "NoSewr", "AllPub"]
exqual_categories = ["N_A", "Po", "Fa", "TA", "Gd", "Ex"]
excond_categories = ["N_A", "Po", "Fa", "TA", "Gd", "Ex"]
bsmtqual_categories = ["N_A", "Po", "Fa", "TA", "Gd", "Ex"]
bsmtcond_categories = ["N_A", "Po", "Fa", "TA", "Gd", "Ex"]
bsmtfintype1_categories = ["N_A", "Unf", "LwQ", "Rec", "BLQ", "ALQ", "GLQ"]
bsmtfintype2_categories = ["N_A", "Unf", "LwQ", "Rec", "BLQ", "ALQ", "GLQ"]
heatingqc_categories = ["N_A", "Po", "Fa", "TA", "Gd", "Ex"]
kitchenqual_categories = ["N_A", "Po", "Fa", "TA", "Gd", "Ex"]
fireplacequ_categories = ["N_A", "Po", "Fa", "TA", "Gd", "Ex"]
garagequal_categories = ["N_A", "Po", "Fa", "TA", "Gd", "Ex"]
garagecond_categories = ["N_A", "Po", "Fa", "TA", "Gd", "Ex"]
fence_categories = ["N_A", "MnWw", "GdWo", "MnPrv", "GdPrv"]
bsmtexposure_categories = ["N_A", "No", "Mn", "Av", "Gd"]
garagefinish_categories = ["N_A", "Unf", "RFn", "Fin"]
paveddrive_categories = ["N_A", "N", "P", "Y"]
lotshape_categories = ["N_A", "IR3", "IR2", "IR1", "Reg"]
landslope_categories = ["N_A", "Sev", "Mod", "Gtl"]
functional_categories = ["N_A", "Sal", "Sev", "Maj2", "Maj1", "Mod", "Min2", "Min1", "Typ"]

ord_encoder = OrdinalEncoder(categories=[utilities_categories, exqual_categories, excond_categories, bsmtqual_categories, bsmtcond_categories, bsmtfintype1_categories, bsmtfintype2_categories, heatingqc_categories, kitchenqual_categories, fireplacequ_categories, garagequal_categories, garagecond_categories, fence_categories, bsmtexposure_categories, garagefinish_categories, paveddrive_categories, lotshape_categories, landslope_categories, functional_categories])

In [136]:
# Identify nominal categorical features (those that will be one-hot encoded)
nominal_features = list(set(cat_features) - set(ordinal_features))
oh_encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

# Combine ordinal and nominal encoders using a column transformer.
cat_encoder = make_column_transformer(
    (ord_encoder, ordinal_features),
    (oh_encoder, nominal_features)
)

# Create a categorical pipeline: imputation followed by encoding.
cat_pipe = make_pipeline(cat_imputer, cat_encoder)

# Combine numerical and categorical pipelines into a full preprocessor.
preprocessor = make_column_transformer(
    (num_pipe, num_features),
    (cat_pipe, cat_features)
)

preprocessor

ColumnTransformer(transformers=[('pipeline-1',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer())]),
                                 Index(['LotArea', 'LotFrontage', 'TotalBsmtSF', 'BedroomAbvGr', 'Fireplaces',
       'PoolArea', 'GarageCars', 'WoodDeckSF', 'ScreenPorch', 'MSSubClass',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea',
       'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', '1stFlrSF...
       'BsmtExposure', 'BsmtFinType1', 'KitchenQual', 'FireplaceQu',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'BsmtFinType2',
       'HeatingQC', 'Electrical', 'Functional', 'GarageType', 'GarageFinish',
       'GarageQual', 'GarageCond', 'PavedDrive', 'Fence', 'SaleType',
       'SaleCondition'],
      dtype='str'))])

## Decision Tree ##

In [137]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeClassifier

# Define a function to perform a grid search, which helps to avoid duplicating code for different models
def run_grid_search(model, param_grid, X_train, y_train, preprocessor, scaler=None, cv=5, verbose=1):
    # Create a pipeline that first applies the data preprocessing steps, then fits the model
    if scaler is None:
        pipe = make_pipeline(preprocessor, model)
    else:
        pipe = make_pipeline(preprocessor, scaler, model)

    # GridSearchCV will test all possible combinations of parameters defined in 'param_grid'
    grid_search = GridSearchCV(pipe, param_grid, cv=cv, verbose=verbose)

    # Fit the model on the training data with the various parameter combinations
    grid_search.fit(X_train, y_train)

    # Return the trained GridSearchCV object which holds the best parameters and model
    return grid_search

# Define a dictionary of hyperparameters to tune for the decision tree model
dt_param_grid = {
    "columntransformer__pipeline-1__simpleimputer__strategy": ["mean", "median"],
    "decisiontreeclassifier__max_depth": range(2, 14, 2),
    "decisiontreeclassifier__min_samples_leaf": range(3, 12, 2)
}

# Run the grid search for the DecisionTreeClassifier using the specified parameters
dt_search = run_grid_search(
    DecisionTreeClassifier(random_state=42),
    dt_param_grid,
    X_train,
    y_train,
    preprocessor
)

# Display the process
dt_search

Fitting 5 folds for each of 60 candidates, totalling 300 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('pipeline-1',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer())]),
                                                                         Index(['LotArea', 'LotFrontage', 'TotalBsmtSF', 'BedroomAbvGr', 'Fireplaces',
       'PoolArea', 'GarageCars', 'WoodDeckSF', 'ScreenPorch', 'MSSubClass',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemod...
       'GarageQual', 'GarageCond', 'PavedDrive', 'Fence', 'SaleType',
       'SaleCondition'],
      dtype='str'))])),
                                       ('decisiontreeclassifier',
                                        DecisionTreeClassifier(random_state=42))]),
             param_grid={'columntransformer__pipeline-1__simpleimputer__strategy': ['mean',
                                                                                    'median'],
                         'decisiontreeclassifier__max_depth': range(2, 14, 2),
                         'decisiontreeclassifier__min_samples_leaf': range(3, 12, 2)},
             verbose=1)

In [138]:
from sklearn.metrics import (
    accuracy_score,
    recall_score,
    precision_score,
    f1_score,
    balanced_accuracy_score,
    cohen_kappa_score
)

# Function to get the scores for our model(s)
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    scores = {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Specificity": recall_score(y_test, y_pred, pos_label=0),
        "F1 Score": f1_score(y_test, y_pred),
        "Balanced Accuracy": balanced_accuracy_score(y_test, y_pred),
        "Cohen's Kappa": cohen_kappa_score(y_test, y_pred)
    }
    return scores

# Create an empty DataFrame to store model evaluation results
model_scores_df = pd.DataFrame(columns=[
    "Model", "Accuracy", "Recall", "Precision",
    "Specificity", "F1 Score", "Balanced Accuracy", "Cohen's Kappa"
])

# Evaluate the Decision Tree model
dt_scores = evaluate_model(dt_search, X_test, y_test)
dt_scores["Model"] = "Decision Tree"

# Convert the dictionary to a Series matching the DataFrame columns, then assign as a new row
model_scores_df.loc[len(model_scores_df)] = pd.Series(dt_scores, index=model_scores_df.columns)

# Display the DataFrame
model_scores_df

,Model,Accuracy,Recall,Precision,Specificity,F1 Score,Balanced Accuracy,Cohen's Kappa
0,Decision Tree,0.938356,0.729167,0.875,0.979508,0.795455,0.854337,0.759517

## KNN ##

In [139]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler


# Define the hyperparameter grid to be searched by the grid search
knn_param_grid = {
    "kneighborsclassifier__n_neighbors": range(3, 30, 2),
    "kneighborsclassifier__weights": ["uniform", "distance"],
    "kneighborsclassifier__p": [1, 2]
}

# Run a grid search to find the optimal combination of hyperparameters
knn_search = run_grid_search(
    KNeighborsClassifier(),
    knn_param_grid,
    X_train,
    y_train,
    preprocessor,
    StandardScaler(),
)

# Display the grid search results
knn_search

Fitting 5 folds for each of 56 candidates, totalling 280 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('pipeline-1',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer())]),
                                                                         Index(['LotArea', 'LotFrontage', 'TotalBsmtSF', 'BedroomAbvGr', 'Fireplaces',
       'PoolArea', 'GarageCars', 'WoodDeckSF', 'ScreenPorch', 'MSSubClass',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemod...
       'HeatingQC', 'Electrical', 'Functional', 'GarageType', 'GarageFinish',
       'GarageQual', 'GarageCond', 'PavedDrive', 'Fence', 'SaleType',
       'SaleCondition'],
      dtype='str'))])),
                                       ('standardscaler', StandardScaler()),
                                       ('kneighborsclassifier',
                                        KNeighborsClassifier())]),
             param_grid={'kneighborsclassifier__n_neighbors': range(3, 30, 2),
                         'kneighborsclassifier__p': [1, 2],
                         'kneighborsclassifier__weights': ['uniform',
                                                           'distance']},
             verbose=1)

In [140]:
# Evaluate the K-Nearest Neighbours (KNN) model using the testing dataset and obtain performance metrics
knn_scores = evaluate_model(knn_search, X_test, y_test)

# Label the metrics to indicate they belong to the KNN model
knn_scores["Model"] = "KNN"
knn_row = pd.DataFrame([knn_scores])

# Append the KNN metrics as a new row to the existing DataFrame of model scores
model_scores_df = pd.concat(
    [model_scores_df[model_scores_df["Model"] != "KNN"], knn_row],
    ignore_index=True
)

# Display the updated DataFrame containing all model performance metrics
model_scores_df

,Model,Accuracy,Recall,Precision,Specificity,F1 Score,Balanced Accuracy,Cohen's Kappa
0,Decision Tree,0.938356,0.729167,0.875,0.979508,0.795455,0.854337,0.759517
1,KNN,0.941781,0.6875,0.942857,0.991803,0.795181,0.839652,0.762215

## Random Forest ##

In [141]:
from sklearn.ensemble import RandomForestClassifier

# Define the hyperparameter grid to be searched by the grid search
rf_param_grid = {
    "randomforestclassifier__n_estimators": [100, 200, 300],
    "randomforestclassifier__max_depth": [4, 6, 8, 10],
    "randomforestclassifier__min_samples_leaf": [3, 5, 10],
    "randomforestclassifier__max_features": ["sqrt", 0.5]
}


# Run a grid search to find the optimal combination of hyperparameters for the Random Forest model
rf_search = run_grid_search(
    model=RandomForestClassifier(random_state=42),
    param_grid=rf_param_grid,
    X_train=X_train,
    y_train=y_train,
    preprocessor=preprocessor
)

# Display the grid search results for the Random Forest model
rf_search

Fitting 5 folds for each of 72 candidates, totalling 360 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('pipeline-1',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer())]),
                                                                         Index(['LotArea', 'LotFrontage', 'TotalBsmtSF', 'BedroomAbvGr', 'Fireplaces',
       'PoolArea', 'GarageCars', 'WoodDeckSF', 'ScreenPorch', 'MSSubClass',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemod...
       'GarageQual', 'GarageCond', 'PavedDrive', 'Fence', 'SaleType',
       'SaleCondition'],
      dtype='str'))])),
                                       ('randomforestclassifier',
                                        RandomForestClassifier(random_state=42))]),
             param_grid={'randomforestclassifier__max_depth': [4, 6, 8, 10],
                         'randomforestclassifier__max_features': ['sqrt', 0.5],
                         'randomforestclassifier__min_samples_leaf': [3, 5, 10],
                         'randomforestclassifier__n_estimators': [100, 200,
                                                                  300]},
             verbose=1)

In [142]:
rf_search.best_params_

{'randomforestclassifier__max_depth': 10,
 'randomforestclassifier__max_features': 0.5,
 'randomforestclassifier__min_samples_leaf': 3,
 'randomforestclassifier__n_estimators': 100}

In [143]:
rf_scores = evaluate_model(rf_search, X_test, y_test)
rf_scores["Model"] = "Random Forest"

rf_row = pd.DataFrame([rf_scores])

model_scores_df = pd.concat(
    [model_scores_df[model_scores_df["Model"] != "Random Forest"], rf_row],
    ignore_index=True
)

model_scores_df

,Model,Accuracy,Recall,Precision,Specificity,F1 Score,Balanced Accuracy,Cohen's Kappa
0,Decision Tree,0.938356,0.729167,0.875,0.979508,0.795455,0.854337,0.759517
1,KNN,0.941781,0.6875,0.942857,0.991803,0.795181,0.839652,0.762215
2,Random Forest,0.955479,0.75,0.972973,0.995902,0.847059,0.872951,0.821516

Random Forest achieved the best F1 score and balanced accuracy.

Decision Tree had strong recall but lower overall performance.

KNN performed well but did not outperform Random Forest.

# Test models for overfitting #

In [144]:
def compare_train_test(model, model_name, X_train, y_train, X_test, y_test):
    train_scores = evaluate_model(model, X_train, y_train)
    test_scores = evaluate_model(model, X_test, y_test)

    train_scores["Model"] = model_name
    train_scores["Dataset"] = "Train"

    test_scores["Model"] = model_name
    test_scores["Dataset"] = "Test"

    return pd.DataFrame([train_scores, test_scores])

In [145]:
overfitting_check = pd.concat(
    [
        compare_train_test(dt_search, "Decision Tree", X_train, y_train, X_test, y_test),
        compare_train_test(knn_search, "KNN", X_train, y_train, X_test, y_test),
        compare_train_test(rf_search, "Random Forest", X_train, y_train, X_test, y_test),
    ],
    ignore_index=True
)

overfitting_check[
    ["Model", "Dataset", "Accuracy", "Recall", "Precision", "F1 Score", "Balanced Accuracy"]
]

,Model,Dataset,Accuracy,Recall,Precision,F1 Score,Balanced Accuracy
0,Decision Tree,Train,0.974315,0.875740,0.942675,0.907975,0.933365
1,Decision Tree,Test,0.938356,0.729167,0.875000,0.795455,0.854337
2,KNN,Train,0.964897,0.810651,0.938356,0.869841,0.900821
3,KNN,Test,0.941781,0.687500,0.942857,0.795181,0.839652
4,Random Forest,Train,0.988870,0.946746,0.975610,0.960961,0.971371
5,Random Forest,Test,0.955479,0.750000,0.972973,0.847059,0.872951

The Random Forest still shows some overfitting, especially in recall, but it now has the strongest test performance of the models tested. The overfitting is acceptable for this stage, though I would still monitor recall because the model misses more expensive houses on test data than on train data.

# Competition test dataset #

Based on test F1 score, balanced accuracy, and overall accuracy, I selected Random Forest as the final model.

In [ ]:
comp_data = pd.read_csv("data/1_classification_competition_test_set.csv")

In [147]:
comp_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   LotArea        1459 non-null   int64
 1   LotFrontage    1232 non-null   float64
 2   TotalBsmtSF    1458 non-null   float64
 3   BedroomAbvGr   1459 non-null   int64
 4   Fireplaces     1459 non-null   int64
 5   PoolArea       1459 non-null   int64
 6   GarageCars     1458 non-null   float64
 7   WoodDeckSF     1459 non-null   int64
 8   ScreenPorch    1459 non-null   int64
 9   MSZoning       1455 non-null   str
 10  Condition1     1459 non-null   str
 11  Heating        1459 non-null   str
 12  Street         1459 non-null   str
 13  CentralAir     1459 non-null   str
 14  Foundation     1459 non-null   str
 15  ExterQual      1459 non-null   str
 16  ExterCond      1459 non-null   str
 17  BsmtQual       1415 non-null   str
 18  BsmtCond       1414 non-null   str
 19  BsmtExposure   1415 non-null   str
 20  BsmtFinType1   1417 non-null   str
 21  KitchenQual    1458 non-null   str
 22  FireplaceQu    729 non-null    str
 23  MSSubClass     1459 non-null   int64
 24  OverallQual    1459 non-null   int64
 25  OverallCond    1459 non-null   int64
 26  YearBuilt      1459 non-null   int64
 27  YearRemodAdd   1459 non-null   int64
 28  MasVnrArea     1444 non-null   float64
 29  BsmtFinSF1     1458 non-null   float64
 30  BsmtFinSF2     1458 non-null   float64
 31  BsmtUnfSF      1458 non-null   float64
 32  1stFlrSF       1459 non-null   int64
 33  2ndFlrSF       1459 non-null   int64
 34  LowQualFinSF   1459 non-null   int64
 35  GrLivArea      1459 non-null   int64
 36  BsmtFullBath   1457 non-null   float64
 37  BsmtHalfBath   1457 non-null   float64
 38  FullBath       1459 non-null   int64
 39  HalfBath       1459 non-null   int64
 40  KitchenAbvGr   1459 non-null   int64
 41  TotRmsAbvGrd   1459 non-null   int64
 42  GarageYrBlt    1381 non-null   float64
 43  GarageArea     1458 non-null   float64
 44  OpenPorchSF    1459 non-null   int64
 45  EnclosedPorch  1459 non-null   int64
 46  3SsnPorch      1459 non-null   int64
 47  MiscVal        1459 non-null   int64
 48  MoSold         1459 non-null   int64
 49  YrSold         1459 non-null   int64
 50  Id             1459 non-null   int64
 51  Alley          107 non-null    str
 52  LotShape       1459 non-null   str
 53  LandContour    1459 non-null   str
 54  Utilities      1457 non-null   str
 55  LotConfig      1459 non-null   str
 56  LandSlope      1459 non-null   str
 57  Neighborhood   1459 non-null   str
 58  Condition2     1459 non-null   str
 59  BldgType       1459 non-null   str
 60  HouseStyle     1459 non-null   str
 61  RoofStyle      1459 non-null   str
 62  RoofMatl       1459 non-null   str
 63  Exterior1st    1458 non-null   str
 64  Exterior2nd    1458 non-null   str
 65  MasVnrType     565 non-null    str
 66  BsmtFinType2   1417 non-null   str
 67  HeatingQC      1459 non-null   str
 68  Electrical     1459 non-null   str
 69  Functional     1457 non-null   str
 70  GarageType     1383 non-null   str
 71  GarageFinish   1381 non-null   str
 72  GarageQual     1381 non-null   str
 73  GarageCond     1381 non-null   str
 74  PavedDrive     1459 non-null   str
 75  PoolQC         3 non-null      str
 76  Fence          290 non-null    str
 77  MiscFeature    51 non-null     str
 78  SaleType       1458 non-null   str
 79  SaleCondition  1459 non-null   str
dtypes: float64(11), int64(26), str(43)
memory usage: 912.0 KB

In [148]:
comp_data.drop(columns=["Alley", "PoolQC", "MiscFeature"], inplace=True)

In [149]:
comp_data = comp_data.set_index("Id")

In [150]:
# Use the best estimator from the Random Forest grid search to make predictions on the competition test dataset
comp_pred = rf_search.best_estimator_.predict(comp_data)
pd.Series(comp_pred).value_counts()

0    1264
1     195
Name: count, dtype: int64

In [151]:
# Create a copy of the competition data and add the predictions as a new column
comp_data_pred = comp_data.copy()
comp_data_pred["Expensive"] = comp_pred

comp_data_pred.head(15)

,LotArea,LotFrontage,TotalBsmtSF,BedroomAbvGr,Fireplaces,PoolArea,GarageCars,WoodDeckSF,ScreenPorch,MSZoning,...,Functional,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,Fence,SaleType,SaleCondition,Expensive
Id,,,,,,,,,,,,,,,,,,,,,
1461,11622,80.0,882.0,2,0,0,1.0,140,120,RH,...,Typ,Attchd,Unf,TA,TA,Y,MnPrv,WD,Normal,0
1462,14267,81.0,1329.0,3,0,0,1.0,393,0,RL,...,Typ,Attchd,Unf,TA,TA,Y,NaN,WD,Normal,0
1463,13830,74.0,928.0,3,1,0,2.0,212,0,RL,...,Typ,Attchd,Fin,TA,TA,Y,MnPrv,WD,Normal,0
1464,9978,78.0,926.0,3,1,0,2.0,360,0,RL,...,Typ,Attchd,Fin,TA,TA,Y,NaN,WD,Normal,0
1465,5005,43.0,1280.0,2,0,0,2.0,0,144,RL,...,Typ,Attchd,RFn,TA,TA,Y,NaN,WD,Normal,0
1466,10000,75.0,763.0,3,1,0,2.0,157,0,RL,...,Typ,Attchd,Fin,TA,TA,Y,NaN,WD,Normal,0
1467,7980,NaN,1168.0,3,0,0,2.0,483,0,RL,...,Typ,Attchd,Fin,TA,TA,Y,GdPrv,WD,Normal,0
1468,8402,63.0,789.0,3,1,0,2.0,0,0,RL,...,Typ,Attchd,Fin,TA,TA,Y,NaN,WD,Normal,0
1469,10176,85.0,1300.0,2,1,0,2.0,192,0,RL,...,Typ,Attchd,Unf,TA,TA,Y,NaN,WD,Normal,0
1470,8400,70.0,882.0,2,0,0,2.0,240,0,RL,...,Typ,Attchd,Fin,TA,TA,Y,MnPrv,WD,Normal,0
1471,5858,26.0,1405.0,2,1,0,2.0,203,0,RH,...,Typ,Attchd,Fin,TA,TA,Y,NaN,WD,Normal,0
1472,1680,21.0,483.0,2,0,0,1.0,275,0,RM,...,Typ,Detchd,Unf,TA,TA,Y,NaN,COD,Normal,0
1473,1680,21.0,525.0,3,0,0,1.0,0,0,RM,...,Typ,Detchd,Unf,TA,TA,Y,NaN,WD,Normal,0
1474,2280,24.0,855.0,3,1,0,2.0,173,0,RL,...,Typ,Attchd,Unf,TA,TA,Y,NaN,WD,Normal,0
1475,2280,24.0,836.0,2,0,0,1.0,0,0,RL,...,Typ,Attchd,Unf,TA,TA,Y,NaN,WD,Normal,0

In [157]:
submission = pd.Series(
    data=comp_pred,
    index=comp_data.index,
    name="Expensive"
)

submission.index.name = "Id"

submission

Id
1461    0
1462    0
1463    0
1464    0
1465    0
       ..
2915    0
2916    0
2917    0
2918    0
2919    0
Name: Expensive, Length: 1459, dtype: int64

In [158]:
submission.to_csv("submission.csv", index=True, header=True)